### ISSUE TITLE
Add IRC link

### ISSUE THREAD

**Issue by 35359595** [Rust-Wroclaw/rust-wroclaw.github.io#1]
Add this or similar to _includel/content.html for live discussion at any time )

`<li><a href='https://client00.chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-wroclaw' title='#rust-wroclaw' target='_blank'>Mozilla IRC Channel</a></li>`

Dont whant to fork/pull req for such small change )
Thanks.

**Comment by MaciekTalaska** [comment]
Thanks! It has been updated!
